source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JMActionSheetDescription_Example', :exclusive => true do
  pod "JMActionSheetDescription", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "JMActionSheetDescription", :path => "../"

  pod 'Kiwi'
  pod 'FBSnapshotTestCase'
end
