source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'JMActionSheetDescription_Example', :exclusive => true do
  pod "JMActionSheetDescription", :path => "../"
  pod 'ionicons'
end
